# Generated by Django 6.0.4 on 2026-04-24 14:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes_app', '0007_alter_viaje_propietario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='viaje',
            options={'ordering': ['-fecha']},
        ),
        migrations.AddField(
            model_name='viaje',
            name='actualizado',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='viaje',
            name='creado',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='viaje',
            name='total_likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
