# Generated by Django 6.0.4 on 2026-04-25 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_infoextra_avatar_alter_infoextra_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='infoextra',
            name='es_privado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='infoextra',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/default.png', null=True, upload_to='avatars/'),
        ),
    ]
