# Generated by Django 6.0.4 on 2026-04-23 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_infoextra_es_privado_seguimiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infoextra',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/default.png', null=True, upload_to='avatars/'),
        ),
    ]
