# Generated by Django 6.0.4 on 2026-04-25 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seguimiento',
            options={'verbose_name': 'Seguimiento', 'verbose_name_plural': 'Seguimientos'},
        ),
        migrations.AlterModelOptions(
            name='solicitudseguimiento',
            options={'verbose_name': 'Solicitud de seguimiento', 'verbose_name_plural': 'Solicitudes de seguimiento'},
        ),
        migrations.AlterField(
            model_name='solicitudseguimiento',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada')], default='pendiente', max_length=10),
        ),
    ]
